### ISSUE TITLE
make this appropriate to deploy to dokku

### ISSUE THREAD

**Issue by skyhighwings** [flixy/flixy#4]
I'm not sure what the fastest and easiest way of doing that would be — Dockerfile or Golang buildpack.

**Comment by Xe** [comment]
![](https://i.kinja-img.com/gawker-media/image/upload/aoz8kgx8pzknypz7z38n.jpg)

**Comment by skyhighwings** [comment]
dockerfile is definitely mandatory either way, because it's just so useful

**Comment by skyhighwings** [comment]
6cedabf508eb718644fed1c4461e479f612ed5f4
